name = "mepet-rumah"
main = "server/worker.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"
binding = "ASSETS"

[vars]
APP_URL = "https://mepet-rumah.mepetrumah.workers.dev"
# JWT_SECRET tidak di sini: lokal pakai .dev.vars, produksi pakai wrangler secret

# Ganti database_id dengan hasil `wrangler d1 create mepetrumah-db`
[[d1_databases]]
binding = "DB"
database_name = "mepetrumah-db"
database_id = "d193b5f8-2368-4edd-87cf-f72e8e544816"
